PidFileLocation: /tmp/wsSocket.pid
proxyList:
  - proxyEntry:
      - wsHost:
          host: 127.0.0.1
          port: 10010
          path: /
      - targetHost:
          host: 127.0.0.1
          port: 10000
          path: /
  - proxyEntry:
      - wsHost:
          host: 127.0.0.1
          port: 10012
          path: /
      - targetHost:
          host: 127.0.0.1
          port: 10002
          path: /
  - proxyEntry:
      - wsHost:
          host: 127.0.0.1
          port: 10014
          path: /
      - targetHost:
          host: 127.0.0.1
          port: 10004
          path: /
